/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ApiTest {
    }
}
declare global {
    interface HTMLApiTestElement extends Components.ApiTest, HTMLStencilElement {
    }
    var HTMLApiTestElement: {
        prototype: HTMLApiTestElement;
        new (): HTMLApiTestElement;
    };
    interface HTMLElementTagNameMap {
        "api-test": HTMLApiTestElement;
    }
}
declare namespace LocalJSX {
    interface ApiTest {
    }
    interface IntrinsicElements {
        "api-test": ApiTest;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "api-test": LocalJSX.ApiTest & JSXBase.HTMLAttributes<HTMLApiTestElement>;
        }
    }
}
